### ISSUE TITLE
Observers todo

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#303]
This is what's still left to implement on the observers branch, from my written notes:
-  User deletes location
  - [x] unsubscribes from public issue threads unless in group or other locations
- User changes setting near_my_locations
  - to automatically follow
    - [x] subscribe to all accessible threads
  - away from follow
    - [x] unsubscribe non-group (if follow group) non participating 
- User changes setting my_groups_matter
  - to automatically follow
    - [x] subscribe to all accessible threads
  - away from follow
    - [x] unsubscribe non location (if follow location) non participating
- User change setting administrative discussion
  - tick
    - [x] subscribe group threads
  - untick
    - [x] unsubscribe discussions

Then:
- [x] remove catchup link / implementation
